= WSL2 Setup 

This repository holds the resources for the setting up a WSL2 instance.

== Ansible

=== Setup

Execute ``./install-ansible-<OS>.sh`` with a sudo user on the WSL2 instance, whereby the repository can be checked out on the Windows host.

Supported OS:

* ``debian``

=== Roles

The following roles are supported by this ansible bundle.

* ``setup`` +
  Installs global packages, modifies the root user and creates the additional users
* ``admin`` +
  Sets up your sudo user
* ``docker`` +
  Delegates to the proper ``docker-<OS>`` role depending on the set variable ``os`` 
* ``docker-debian`` +
  Installs Docker globally on a debian OD 
* ``kind`` +
  Install kind globally 
* ``podman`` +
  Delegates to the proper ``podman-<OS>`` role depending on the set variable ``os`` 
* ``podman-debian`` +
  Install the tool Podman globally

=== Execute 

Create a ``variables.yml`` file in the ``./ansible`` directory which contains the necessary variables. You can have multiple variable definitions but you should name them ``<PREFIX>variables.[yml|yaml]`` which are excluded for git.

.YAML configuration file 
[code, yaml]
----
# The OS you want to install docker on [debian]
os: ""
# The sudo user of your WSL2 instance (not root)
sudo_user: ""
# The fully qualified mounted Windows path linked to /home/<username>/win
win_home: ""
# The fully qualified mounted Windows path to the openssh private key file
id_rsa: ""
# The version of kind provided by the github repository
kind_version: "v0.8.1"
# (Optional) The list of addditional users to create
users:
    - additional_user1
    - additional_user2
----

Execute the following command in the directory link:./ansible[./ansible] to setup the WSL2 Debian instance with Ansible.

.Shell command for executing the bundle
[code, bash]
----
ansible-playbook site.yml -e @variables.yml -e id_rsa_pass=<SSH_PRIVATE_KEY_PASS>
----

TIP: You can reach the Windows folders under ``/mnt/c/..``. 

== Docker

You need to start docker manually since we don't have a systemd managed OS, meaning the OS never starts up.

.Start the Docker service
[source,bash]
-----
sudo service docker start
-----

.Test if Docker is up and running
[source,bash]
-----
docker ps
-----

== Kind

``kind`` is a tool for povisioning a single node Kubernetes Cluster in Docker. +
See link:https://kind.sigs.k8s.io/docs[Kind Doc] for the documentation of kind.

== Podman

``Podman`` is a tool similar to Docker but doesn't rely on a daemon to manage containers. +
See link:https://podman.io/[Podman doc] for the documentation of Podman.

.Test if Podmanis working
[source,bash]
-----
podman run hello-world
-----

TIP: Podman and Docker don't share the same registry so container images get downloaded either for Podman or Docker