= WSL2 Setup 

This repository holds the resources for the setting up a WSL2 instance.

== Ansible

=== Setup

Execute ``./install-ansible-<OS>.sh`` with a sudo user on the WSL2 instance, whereby the repository can be checked out on the Windows host.

Supported OS:

* ``debian``

== OS specific setup

=== Debian

Docker on Debian 10 (Buster) down't work with ``iptables=true``, which is due to the new iptables implementation. Therefore this bundle will set the iptables alternative to ``iptables-legacy``.

=== Roles

The following roles are supported by this ansible bundle.

* ``setup`` +
  Installs global packages, modifies the root user and creates the additional users
* ``admin`` +
  Sets up your sudo user
* ``docker`` +
  Delegates to the proper ``docker-<OS>`` role depending on the set variable ``os`` 
* ``docker-debian`` +
  Installs Docker globally on a Debian OS
* ``kind`` +
  Install kind globally 
* ``podman`` +
  Delegates to the proper ``podman-<OS>`` role depending on the set variable ``os`` 
* ``podman-debian`` +
  Install the tool Podman globally on a Debian OS
* ``buildah`` +
  Delegates to the proper ``buildah-<OS>`` role depending on the set variable ``os`` 
* ``buildah-debian`` +
  Install the tool Buildah globally on a Debian OS
* ``kubectl`` +
  Delegates to the proper ``buildah-<OS>`` role depending on the set variable ``os`` 
* ``kubectl-debian-ubuntu`` +
  Install the tool Kubectl globally on a Debian/Ubuntu OS

=== Configuration 

Create a ``variables.yml`` file in the ``./ansible`` directory which contains the necessary variables. You can have multiple variable definitions but you should name them ``<PREFIX>variables.[yml|yaml]`` which are excluded for git.

.YAML configuration file 
[code, yaml]
----
# The OS you want to install docker on [debian]
os: ""
# The sudo user of your WSL2 instance (not root)
sudo_user: ""
# The fully qualified mounted Windows path linked to /home/<username>/win
win_home: ""
# The fully qualified mounted Windows path to the openssh private key file
id_rsa: ""
# The version of kind provided by the github repository
kind_version: "v0.8.1"
# (Optional) The list of addditional users to create
users:
    - additional_user1
    - additional_user2
----

TIP: You can reach the Windows folders under ``/mnt/c/..``. 

=== Playbooks 

Execute the following commands in the directory link:./ansible[./ansible].

.Setup the WSL2 instance
[code, bash]
----
ansible-playbook site.yml --ask-become-pass -e @variables.yml -e id_rsa_pass=<SSH_PRIVATE_KEY_PASS>
----

.Start the Docker Service (after each WSL2 start)
[code, bash]
----
ansible-playbook start-docker.yml --ask-become-pass -e @variables.yml
----

== Docker

You need to start docker manually since we don't have a systemd managed OS, meaning the OS never starts up.

.Test if Docker is up and running
[source,bash]
-----
docker ps
-----

.Test if Docker works
[source,bash]
-----
docker run hello-world
-----

== Kind

``kind`` is a tool for povisioning a single node Kubernetes Cluster in Docker. +
See link:https://kind.sigs.k8s.io/docs[Kind Doc] for the documentation of kind.

== Podman

``Podman`` is a tool similar to Docker but doesn't rely on a daemon to manage containers. +
See link:https://podman.io/[Podman doc] for the documentation of Podman.

.Test if Podman is working
[source,bash]
-----
podman run hello-world
-----

TIP: Podman and Docker don't share the same registry so container images get downloaded either for Podman or Docker

== Buildah 

``Buildah`` is a tool for managing Container Images without Docker. It mostly replaces the Dockerfile and allows you to build Container images in a shell script. +
See link:https://buildah.io/[Buildah doc] for the documentation of Buildah.

.Test if buildah works
[source,bash]
-----
cd ./test/buildah
buildah bud -t test-buildah:latest .
-----