- name: "Remove obsolete global packages"
  package:
    name: "{{ item }}"
    state: absent
    update_cache: yes
  with_items:
    - docker
    - docker-engine
    - docker.io 
    - containerd 
    - runc

- name: "Install global packages"
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
      - gpg
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: "Debian specific setup"
  include: setup-debian.yml
  when: os == 'debian'