- name: "Add Buildah repository gpg key"
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/Debian_10/Release.key
    state: "{{ state }}" 

- name: "Add Buildah repository"
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /
    state: "{{ state }}"
    filename: kubic-debian

- name: "Install Buildah packages"
  apt:
    name: "{{ item }}"
    state: "{{ state }}"
    update_cache: yes
  loop:
    - "buildah"