- name: "Create the group '{{ username }}'"
  group:
    name: "{{ username }}"
    state: present

- name: "Create user '{{ username }}' directories"
  file:
    path: "/home/{{ username }}/{{ item }}"
    state: "directory"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0755
  with_items:
    - ".local/bin"

- name: "Create user '{{ username }}'"
  user:
     name: "{{ username }}"
     shell: /bin/bash
     createhome: yes
     group: "{{ group }}"
     groups: "{{ additional_groups }}"
     force: no
     remove: no

- name: "Set proper permissions on '/home/{{ username }}'"
  file:
    path: "/home/{{ username }}"
    state: "directory"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0755

- name: "Symlink to Windows Home '/home/{{ username }}/win'"
  file:
    src: "{{ win_home }}"
    path: "/home/{{ username }}/win"
    state: "link"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0755

- name: "Create '/home/{{ username }}/.ssh'"
  file:
    path: "/home/{{ username }}/.ssh"
    state: "directory"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0700

- name: "Add files to '/home/{{ username }}/'"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0600
  with_items:
    - { src: "../templates/.bashrc", dest: "/home/{{ username }}/.bashrc" }
    - { src: "{{ id_rsa }}", dest: "/home/{{ username }}/.ssh/id_rsa" }

- name: "Create ssh public key from the provided private key"
  expect: 
    command: "/bin/bash -c 'ssh-keygen -y -f /home/{{ username }}/.ssh/id_rsa > /home/{{ username }}/.ssh/id_rsa.pub'"
    responses:
      (.*)pass(.*): "{{ id_rsa_pass }}"

- name: "Add user aliases"
  blockinfile:
    path: "/home/{{ username }}/.bashrc"
    marker: "# {mark} alias {{ item.alias }}"
    block: "alias {{ item.alias }}='{{ item.cmd }}'"
  with_items: "{{ aliases }}"
  when: aliases is defined and aliases | length > 0