- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: "{{ state }}"  

- name: ""
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: "{{ state }}"
    filename: docker-debian

- name: "Install packages"
  apt:
    name: "{{ item }}"
    state: "{{ state }}"
    update_cache: yes
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io