- name: "Add Kubectl repository gpg key"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: "{{ state }}" 

- name: "Add Kubectl repository"
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: "{{ state }}"
    filename: kubectl-debian

- name: "Install Kubectl packages"
  apt:
    name: "{{ item }}"
    state: "{{ state }}"
    update_cache: yes
  loop:
    - "kubectl"