- name: "Install git"
  package:
    name: "git"
    state: present
    update_cache: yes

- name: "Set core.editor = 'nano'"
  git_config:
    name: core.editor
    scope: system
    value: "nano"
    
- name: "Set git core.autocrlf = input"
  git_config:
    name: core.autocrlf
    scope: system
    value: "input"
    
- name: "Set git user.name = {{ git_username }}"
  git_config:
    name: user.name
    scope: system
    value: "{{ git_username }}"

- name: "Set git user.email = {{ git_email }}"
  git_config:
    name: user.email
    scope: system
    value: "{{ git_email }}"

- name: "Set git http.sslVerify = {{ git_http_ssl_verify }}"
  git_config:
    name: http.sslVerify
    scope: system 
    value: "{{ git_http_ssl_verify }}"
