- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/Release.key
    state: "{{ state }}" 

- name: ""
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /
    state: "{{ state }}"
    filename: podman-debian

- name: "Install packages"
  apt:
    name: "{{ item }}"
    state: "{{ state }}"
    update_cache: yes
  loop:
    - "podman"