- name: "Add Podman repository gpg key"
  apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/Release.key
    state: "{{ state }}" 

- name: "Add Podman repository"
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /
    state: "{{ state }}"
    filename: kubic-debian

- name: "Install Podman packages"
  apt:
    name: "{{ item }}"
    state: "{{ state }}"
    update_cache: yes
  loop:
    - "podman"