- hosts: 
    - localhost
  remote_user: "{{ sudo_user }}"
  gather_facts: yes
  become: yes
  become_method: sudo
  roles:
    - setup
    - git
    - user
    - kind
    - podman
    - docker
    - buildah 
    - kubectl